{
  imports = [
    ./lualine.nix
    ./neotree.nix
    ./mini.nix
    ./telescope.nix
    ./barbar.nix
    ./nix.nix
    ./lsp.nix
    ./cmp.nix
    ./treesitter.nix
    ./wilder.nix
    ./whichKey.nix
    ./comment.nix
    ./diffview.nix
    ./markdown-preview.nix
    ./zig.nix
    ./luasnip.nix
    ./lazy.nix
  ];
}
